### ISSUE TITLE
Fatal Error: Out of memory when using the program

### ISSUE THREAD

**Issue by jason-anca** [leotaku/kojirou#39]
Hey Folks!
I wanted to start off by saying thanks for creating this! Been having trouble putting Manga on my Kindle and this has been the most intuitive solution so thanks!

I've checked both open and closed issues just in case this has issue has been raised before but it either doesn't exist or I'm just blind so I wanna apologize if this has been raised before.

I ran the following command in order to try and get the "Sousou no Frieren" manga off of Mangadex:
`kojirou b0b721ff-c388-4486-aa0f-c2b0bb321512 -l en --kindle-folder-mode`

The command worked fine until about volume 8 when a out of memory error was thrown.
![image](https://github.com/leotaku/kojirou/assets/47369830/98b4cc0a-1df0-4be9-b7ca-f1d49be744c5)

And also had this fairly large error thrown out afterwards. I'm not all too familiar with Go so I have no idea what information this provides, even as a fellow developer.
```
goroutine 1 [running]:
runtime.throw({0x11116a9, 0xd})
        C:/Program Files (x86)/Go/src/runtime/panic.go:1077 +0x4d fp=0x10f51434 sp=0x10f51420 pc=0xcbd7ed
runtime.(*mcache).allocLarge(0xc202d8, 0xc200000, 0x1)
        C:/Program Files (x86)/Go/src/runtime/mcache.go:236 +0x1c5 fp=0x10f51460 sp=0x10f51434 pc=0xc982b5
runtime.mallocgc(0xc200000, 0x0, 0x0)
        C:/Program Files (x86)/Go/src/runtime/malloc.go:1123 +0x5bd fp=0x10f514b4 sp=0x10f51460 pc=0xc8fe5d
runtime.growslice(0x0, 0xc200000, 0x0, 0xc200000, 0x10a5840)
        C:/Program Files (x86)/Go/src/runtime/slice.go:266 +0x3d1 fp=0x10f514e8 sp=0x10f514b4 pc=0xcd4621
bytes.growSlice({0x473fa000, 0x606b41b, 0x6100000}, 0xdf78d)
        C:/Program Files (x86)/Go/src/bytes/buffer.go:249 +0x9e fp=0x10f51524 sp=0x10f514e8 pc=0xd84b5e
bytes.(*Buffer).grow(0x115a8ea0, 0xdf78d)
        C:/Program Files (x86)/Go/src/bytes/buffer.go:151 +0x110 fp=0x10f5154c sp=0x10f51524 pc=0xd84610
bytes.(*Buffer).Write(0x115a8ea0, {0x31116002, 0xdf78d, 0xffffe})
        C:/Program Files (x86)/Go/src/bytes/buffer.go:179 +0x4a fp=0x10f51560 sp=0x10f5154c pc=0xd847ba
github.com/leotaku/mobi/jfif.Encode({0x11bc158, 0x115a8ea0}, {0x11bde30, 0x38c30f90}, 0x0)
        C:/Users/Jason/go/pkg/mod/github.com/leotaku/mobi@v0.0.0-20230426193406-3c3105acd3e2/jfif/jfif.go:36 +0x11b fp=0x10f51594 sp=0x10f51560 pc=0x1005c0b
github.com/leotaku/mobi/records.ImageRecord.Write(...)
        C:/Users/Jason/go/pkg/mod/github.com/leotaku/mobi@v0.0.0-20230426193406-3c3105acd3e2/records/image.go:21
github.com/leotaku/mobi/records.(*ImageRecord).Write(0x2d802360, {0x11bc158, 0x115a8ea0})
        <autogenerated>:1 +0x4b fp=0x10f515b4 sp=0x10f51594 pc=0x1009a3b
github.com/leotaku/mobi/pdb.Database.Write({{0xc289818, 0x14}, {0x0, 0xe7791f700, 0x1495640}, {0xd1cd800, 0xd5, 0x100}}, {0x11bbfdc, 0x11374ee0})
        C:/Users/Jason/go/pkg/mod/github.com/leotaku/mobi@v0.0.0-20230426193406-3c3105acd3e2/pdb/pdb.go:68 +0x207 fp=0x10f51704 sp=0x10f515b4 pc=0x1005247
github.com/leotaku/kojirou/cmd/formats/kindle.(*NormalizedDirectory).Write(0x10f51b84, {0x0, 0x8, 0x0, {0x0, 0x0}}, {{0xc289818, 0x14}, {0xa4b0030, 0x1, ...}, ...}, ...)
        C:/Users/Jason/go/pkg/mod/github.com/leotaku/kojirou@v0.3.1/cmd/formats/kindle/filesystem.go:61 +0x234 fp=0x10f51854 sp=0x10f51704 pc=0x1020114
github.com/leotaku/kojirou/cmd.handleVolume({{{0xa5d4078, 0x11}, {0xa4b0030, 0x1, 0x1}, {0xa4b0038, 0x1, 0x1}, {0xa5d8060, 0x24}}, ...}, ...)
        C:/Users/Jason/go/pkg/mod/github.com/leotaku/kojirou@v0.3.1/cmd/business.go:76 +0x6c5 fp=0x10f51b38 sp=0x10f51854 pc=0x10672c5
github.com/leotaku/kojirou/cmd.run()
        C:/Users/Jason/go/pkg/mod/github.com/leotaku/kojirou@v0.3.1/cmd/business.go:41 +0x87b fp=0x10f51e78 sp=0x10f51b38 pc=0x1066adb
github.com/leotaku/kojirou/cmd.glob..func1(0x1490a00, {0xa423180, 0x1, 0x4})
        C:/Users/Jason/go/pkg/mod/github.com/leotaku/kojirou@v0.3.1/cmd/root.go:41 +0x5a fp=0x10f51e84 sp=0x10f51e78 pc=0x1069aca
github.com/spf13/cobra.(*Command).execute(0x1490a00, {0xa428088, 0x4, 0x7})
        C:/Users/Jason/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x87e fp=0x10f51f20 sp=0x10f51e84 pc=0x104916e
github.com/spf13/cobra.(*Command).ExecuteC(0x1490a00)
        C:/Users/Jason/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x40e fp=0x10f51f8c sp=0x10f51f20 pc=0x104995e
github.com/spf13/cobra.(*Command).Execute(...)
        C:/Users/Jason/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/leotaku/kojirou/cmd.Execute()
        C:/Users/Jason/go/pkg/mod/github.com/leotaku/kojirou@v0.3.1/cmd/root.go:149 +0x47 fp=0x10f51fa0 sp=0x10f51f8c pc=0x1069c07
main.main()
        C:/Users/Jason/go/pkg/mod/github.com/leotaku/kojirou@v0.3.1/kojirou.go:6 +0x15 fp=0x10f51fa4 sp=0x10f51fa0 pc=0x106ab85
runtime.main()
        C:/Program Files (x86)/Go/src/runtime/proc.go:267 +0x2b7 fp=0x10f51ff0 sp=0x10f51fa4 pc=0xcc03c7
runtime.goexit()
        C:/Program Files (x86)/Go/src/runtime/asm_386.s:1363 +0x1 fp=0x10f51ff4 sp=0x10f51ff0 pc=0xcef771

goroutine 2 [force gc (idle), 2 minutes]:
runtime.gopark(0x1143cf4, 0x1494c80, 0x11, 0x14, 0x1)
        C:/Program Files (x86)/Go/src/runtime/proc.go:398 +0xfd fp=0xa449fdc sp=0xa449fc8 pc=0xcc083d
runtime.goparkunlock(...)
        C:/Program Files (x86)/Go/src/runtime/proc.go:404
runtime.forcegchelper()
        C:/Program Files (x86)/Go/src/runtime/proc.go:322 +0xcf fp=0xa449ff0 sp=0xa449fdc pc=0xcc068f
runtime.goexit()
        C:/Program Files (x86)/Go/src/runtime/asm_386.s:1363 +0x1 fp=0xa449ff4 sp=0xa449ff0 pc=0xcef771
created by runtime.init.5 in goroutine 1
        C:/Program Files (x86)/Go/src/runtime/proc.go:310 +0x21

goroutine 3 [GC sweep wait]:
runtime.gopark(0x1143cf4, 0x1495440, 0xc, 0x14, 0x1)
        C:/Program Files (x86)/Go/src/runtime/proc.go:398 +0xfd fp=0xa44afcc sp=0xa44afb8 pc=0xcc083d
runtime.goparkunlock(...)
        C:/Program Files (x86)/Go/src/runtime/proc.go:404
runtime.bgsweep(0xa41a100)
        C:/Program Files (x86)/Go/src/runtime/mgcsweep.go:321 +0xf4 fp=0xa44afe8 sp=0xa44afcc pc=0xcaa2c4
runtime.gcenable.func1()
        C:/Program Files (x86)/Go/src/runtime/mgc.go:200 +0x25 fp=0xa44aff0 sp=0xa44afe8 pc=0xc9c2a5
runtime.goexit()
        C:/Program Files (x86)/Go/src/runtime/asm_386.s:1363 +0x1 fp=0xa44aff4 sp=0xa44aff0 pc=0xcef771
created by runtime.gcenable in goroutine 1
        C:/Program Files (x86)/Go/src/runtime/mgc.go:200 +0x75

goroutine 4 [GC scavenge wait]:
runtime.gopark(0x1143cf4, 0x14957c0, 0xd, 0x14, 0x2)
        C:/Program Files (x86)/Go/src/runtime/proc.go:398 +0xfd fp=0xa44bfb8 sp=0xa44bfa4 pc=0xcc083d
runtime.goparkunlock(...)
        C:/Program Files (x86)/Go/src/runtime/proc.go:404
runtime.(*scavengerState).park(0x14957c0)
        C:/Program Files (x86)/Go/src/runtime/mgcscavenge.go:425 +0x5c fp=0xa44bfcc sp=0xa44bfb8 pc=0xca764c
runtime.bgscavenge(0xa41a100)
        C:/Program Files (x86)/Go/src/runtime/mgcscavenge.go:658 +0x6d fp=0xa44bfe8 sp=0xa44bfcc pc=0xca7ccd
runtime.gcenable.func2()
        C:/Program Files (x86)/Go/src/runtime/mgc.go:201 +0x25 fp=0xa44bff0 sp=0xa44bfe8 pc=0xc9c265
runtime.goexit()
        C:/Program Files (x86)/Go/src/runtime/asm_386.s:1363 +0x1 fp=0xa44bff4 sp=0xa44bff0 pc=0xcef771
created by runtime.gcenable in goroutine 1
        C:/Program Files (x86)/Go/src/runtime/mgc.go:201 +0xb5

goroutine 5 [finalizer wait]:
runtime.gopark(0x1143b8c, 0x14bc2b8, 0x10, 0x14, 0x1)
        C:/Program Files (x86)/Go/src/runtime/proc.go:398 +0xfd fp=0xa448f98 sp=0xa448f84 pc=0xcc083d
runtime.runfinq()
        C:/Program Files (x86)/Go/src/runtime/mfinal.go:193 +0xf8 fp=0xa448ff0 sp=0xa448f98 pc=0xc9b418
runtime.goexit()
        C:/Program Files (x86)/Go/src/runtime/asm_386.s:1363 +0x1 fp=0xa448ff4 sp=0xa448ff0 pc=0xcef771
created by runtime.createfing in goroutine 1
        C:/Program Files (x86)/Go/src/runtime/mfinal.go:163 +0x5e

goroutine 16 [GC worker (idle)]:
runtime.gopark(0x1143ba0, 0xa5d4258, 0x1a, 0x14, 0x0)
        C:/Program Files (x86)/Go/src/runtime/proc.go:398 +0xfd fp=0xa447f94 sp=0xa447f80 pc=0xcc083d
runtime.gcBgMarkWorker()
        C:/Program Files (x86)/Go/src/runtime/mgc.go:1293 +0xdc fp=0xa447ff0 sp=0xa447f94 pc=0xc9e50c
runtime.goexit()
        C:/Program Files (x86)/Go/src/runtime/asm_386.s:1363 +0x1 fp=0xa447ff4 sp=0xa447ff0 pc=0xcef771
created by runtime.gcBgMarkStartWorkers in goroutine 1
        C:/Program Files (x86)/Go/src/runtime/mgc.go:1217 +0x23

goroutine 15 [GC worker (idle)]:
runtime.gopark(0x1143ba0, 0xa416d98, 0x1a, 0x14, 0x0)
        C:/Program Files (x86)/Go/src/runtime/proc.go:398 +0xfd fp=0xa446f94 sp=0xa446f80 pc=0xcc083d
runtime.gcBgMarkWorker()
        C:/Program Files (x86)/Go/src/runtime/mgc.go:1293 +0xdc fp=0xa446ff0 sp=0xa446f94 pc=0xc9e50c
runtime.goexit()
        C:/Program Files (x86)/Go/src/runtime/asm_386.s:1363 +0x1 fp=0xa446ff4 sp=0xa446ff0 pc=0xcef771
created by runtime.gcBgMarkStartWorkers in goroutine 1
        C:/Program Files (x86)/Go/src/runtime/mgc.go:1217 +0x23

goroutine 50 [GC worker (idle)]:
runtime.gopark(0x1143ba0, 0xa5d4270, 0x1a, 0x14, 0x0)
        C:/Program Files (x86)/Go/src/runtime/proc.go:398 +0xfd fp=0xa656f94 sp=0xa656f80 pc=0xcc083d
runtime.gcBgMarkWorker()
        C:/Program Files (x86)/Go/src/runtime/mgc.go:1293 +0xdc fp=0xa656ff0 sp=0xa656f94 pc=0xc9e50c
runtime.goexit()
        C:/Program Files (x86)/Go/src/runtime/asm_386.s:1363 +0x1 fp=0xa656ff4 sp=0xa656ff0 pc=0xcef771
created by runtime.gcBgMarkStartWorkers in goroutine 1
        C:/Program Files (x86)/Go/src/runtime/mgc.go:1217 +0x23

goroutine 19 [GC worker (idle)]:
runtime.gopark(0x1143ba0, 0xa4981c8, 0x1a, 0x14, 0x0)
        C:/Program Files (x86)/Go/src/runtime/proc.go:398 +0xfd fp=0xa445f94 sp=0xa445f80 pc=0xcc083d
runtime.gcBgMarkWorker()
        C:/Program Files (x86)/Go/src/runtime/mgc.go:1293 +0xdc fp=0xa445ff0 sp=0xa445f94 pc=0xc9e50c
runtime.goexit()
        C:/Program Files (x86)/Go/src/runtime/asm_386.s:1363 +0x1 fp=0xa445ff4 sp=0xa445ff0 pc=0xcef771
created by runtime.gcBgMarkStartWorkers in goroutine 1
        C:/Program Files (x86)/Go/src/runtime/mgc.go:1217 +0x23

goroutine 35 [GC worker (idle)]:
runtime.gopark(0x1143ba0, 0xa5d4240, 0x1a, 0x14, 0x0)
        C:/Program Files (x86)/Go/src/runtime/proc.go:398 +0xfd fp=0xa444f94 sp=0xa444f80 pc=0xcc083d
runtime.gcBgMarkWorker()
        C:/Program Files (x86)/Go/src/runtime/mgc.go:1293 +0xdc fp=0xa444ff0 sp=0xa444f94 pc=0xc9e50c
runtime.goexit()
        C:/Program Files (x86)/Go/src/runtime/asm_386.s:1363 +0x1 fp=0xa444ff4 sp=0xa444ff0 pc=0xcef771
created by runtime.gcBgMarkStartWorkers in goroutine 1
        C:/Program Files (x86)/Go/src/runtime/mgc.go:1217 +0x23

goroutine 36 [GC worker (idle)]:
runtime.gopark(0x1143ba0, 0xa498138, 0x1a, 0x14, 0x0)
        C:/Program Files (x86)/Go/src/runtime/proc.go:398 +0xfd fp=0xa8e4f94 sp=0xa8e4f80 pc=0xcc083d
runtime.gcBgMarkWorker()
        C:/Program Files (x86)/Go/src/runtime/mgc.go:1293 +0xdc fp=0xa8e4ff0 sp=0xa8e4f94 pc=0xc9e50c
runtime.goexit()
        C:/Program Files (x86)/Go/src/runtime/asm_386.s:1363 +0x1 fp=0xa8e4ff4 sp=0xa8e4ff0 pc=0xcef771
created by runtime.gcBgMarkStartWorkers in goroutine 1
        C:/Program Files (x86)/Go/src/runtime/mgc.go:1217 +0x23

goroutine 37 [GC worker (idle)]:
runtime.gopark(0x1143ba0, 0xa498150, 0x1a, 0x14, 0x0)
        C:/Program Files (x86)/Go/src/runtime/proc.go:398 +0xfd fp=0xa8e5f94 sp=0xa8e5f80 pc=0xcc083d
runtime.gcBgMarkWorker()
        C:/Program Files (x86)/Go/src/runtime/mgc.go:1293 +0xdc fp=0xa8e5ff0 sp=0xa8e5f94 pc=0xc9e50c
runtime.goexit()
        C:/Program Files (x86)/Go/src/runtime/asm_386.s:1363 +0x1 fp=0xa8e5ff4 sp=0xa8e5ff0 pc=0xcef771
created by runtime.gcBgMarkStartWorkers in goroutine 1
        C:/Program Files (x86)/Go/src/runtime/mgc.go:1217 +0x23

goroutine 38 [GC worker (idle)]:
runtime.gopark(0x1143ba0, 0xa498168, 0x1a, 0x14, 0x0)
        C:/Program Files (x86)/Go/src/runtime/proc.go:398 +0xfd fp=0xa8e6f94 sp=0xa8e6f80 pc=0xcc083d
runtime.gcBgMarkWorker()
        C:/Program Files (x86)/Go/src/runtime/mgc.go:1293 +0xdc fp=0xa8e6ff0 sp=0xa8e6f94 pc=0xc9e50c
runtime.goexit()
        C:/Program Files (x86)/Go/src/runtime/asm_386.s:1363 +0x1 fp=0xa8e6ff4 sp=0xa8e6ff0 pc=0xcef771
created by runtime.gcBgMarkStartWorkers in goroutine 1
        C:/Program Files (x86)/Go/src/runtime/mgc.go:1217 +0x23

goroutine 39 [GC worker (idle)]:
runtime.gopark(0x1143ba0, 0xa498180, 0x1a, 0x14, 0x0)
        C:/Program Files (x86)/Go/src/runtime/proc.go:398 +0xfd fp=0xa8e7f94 sp=0xa8e7f80 pc=0xcc083d
runtime.gcBgMarkWorker()
        C:/Program Files (x86)/Go/src/runtime/mgc.go:1293 +0xdc fp=0xa8e7ff0 sp=0xa8e7f94 pc=0xc9e50c
runtime.goexit()
        C:/Program Files (x86)/Go/src/runtime/asm_386.s:1363 +0x1 fp=0xa8e7ff4 sp=0xa8e7ff0 pc=0xcef771
created by runtime.gcBgMarkStartWorkers in goroutine 1
        C:/Program Files (x86)/Go/src/runtime/mgc.go:1217 +0x23

goroutine 40 [GC worker (idle)]:
runtime.gopark(0x1143ba0, 0xa498198, 0x1a, 0x14, 0x0)
        C:/Program Files (x86)/Go/src/runtime/proc.go:398 +0xfd fp=0xa8e0f94 sp=0xa8e0f80 pc=0xcc083d
runtime.gcBgMarkWorker()
        C:/Program Files (x86)/Go/src/runtime/mgc.go:1293 +0xdc fp=0xa8e0ff0 sp=0xa8e0f94 pc=0xc9e50c
runtime.goexit()
        C:/Program Files (x86)/Go/src/runtime/asm_386.s:1363 +0x1 fp=0xa8e0ff4 sp=0xa8e0ff0 pc=0xcef771
created by runtime.gcBgMarkStartWorkers in goroutine 1
        C:/Program Files (x86)/Go/src/runtime/mgc.go:1217 +0x23

goroutine 41 [GC worker (idle)]:
runtime.gopark(0x1143ba0, 0xa4981b0, 0x1a, 0x14, 0x0)
        C:/Program Files (x86)/Go/src/runtime/proc.go:398 +0xfd fp=0xa8e1f94 sp=0xa8e1f80 pc=0xcc083d
runtime.gcBgMarkWorker()
        C:/Program Files (x86)/Go/src/runtime/mgc.go:1293 +0xdc fp=0xa8e1ff0 sp=0xa8e1f94 pc=0xc9e50c
runtime.goexit()
        C:/Program Files (x86)/Go/src/runtime/asm_386.s:1363 +0x1 fp=0xa8e1ff4 sp=0xa8e1ff0 pc=0xcef771
created by runtime.gcBgMarkStartWorkers in goroutine 1
        C:/Program Files (x86)/Go/src/runtime/mgc.go:1217 +0x23

goroutine 42 [GC worker (idle)]:
runtime.gopark(0x1143ba0, 0xa416d50, 0x1a, 0x14, 0x0)
        C:/Program Files (x86)/Go/src/runtime/proc.go:398 +0xfd fp=0xa8e2f94 sp=0xa8e2f80 pc=0xcc083d
runtime.gcBgMarkWorker()
        C:/Program Files (x86)/Go/src/runtime/mgc.go:1293 +0xdc fp=0xa8e2ff0 sp=0xa8e2f94 pc=0xc9e50c
runtime.goexit()
        C:/Program Files (x86)/Go/src/runtime/asm_386.s:1363 +0x1 fp=0xa8e2ff4 sp=0xa8e2ff0 pc=0xcef771
created by runtime.gcBgMarkStartWorkers in goroutine 1
        C:/Program Files (x86)/Go/src/runtime/mgc.go:1217 +0x23

goroutine 20 [GC worker (idle)]:
runtime.gopark(0x1143ba0, 0xa416d68, 0x1a, 0x14, 0x0)
        C:/Program Files (x86)/Go/src/runtime/proc.go:398 +0xfd fp=0xa692f94 sp=0xa692f80 pc=0xcc083d
runtime.gcBgMarkWorker()
        C:/Program Files (x86)/Go/src/runtime/mgc.go:1293 +0xdc fp=0xa692ff0 sp=0xa692f94 pc=0xc9e50c
runtime.goexit()
        C:/Program Files (x86)/Go/src/runtime/asm_386.s:1363 +0x1 fp=0xa692ff4 sp=0xa692ff0 pc=0xcef771
created by runtime.gcBgMarkStartWorkers in goroutine 1
        C:/Program Files (x86)/Go/src/runtime/mgc.go:1217 +0x23

goroutine 43 [GC worker (idle)]:
runtime.gopark(0x1143ba0, 0xa4981e0, 0x1a, 0x14, 0x0)
        C:/Program Files (x86)/Go/src/runtime/proc.go:398 +0xfd fp=0xa8e3f94 sp=0xa8e3f80 pc=0xcc083d
runtime.gcBgMarkWorker()
        C:/Program Files (x86)/Go/src/runtime/mgc.go:1293 +0xdc fp=0xa8e3ff0 sp=0xa8e3f94 pc=0xc9e50c
runtime.goexit()
        C:/Program Files (x86)/Go/src/runtime/asm_386.s:1363 +0x1 fp=0xa8e3ff4 sp=0xa8e3ff0 pc=0xcef771
created by runtime.gcBgMarkStartWorkers in goroutine 1
        C:/Program Files (x86)/Go/src/runtime/mgc.go:1217 +0x23

goroutine 44 [GC worker (idle)]:
runtime.gopark(0x1143ba0, 0xa416d80, 0x1a, 0x14, 0x0)
        C:/Program Files (x86)/Go/src/runtime/proc.go:398 +0xfd fp=0xa68ef94 sp=0xa68ef80 pc=0xcc083d
runtime.gcBgMarkWorker()
        C:/Program Files (x86)/Go/src/runtime/mgc.go:1293 +0xdc fp=0xa68eff0 sp=0xa68ef94 pc=0xc9e50c
runtime.goexit()
        C:/Program Files (x86)/Go/src/runtime/asm_386.s:1363 +0x1 fp=0xa68eff4 sp=0xa68eff0 pc=0xcef771
created by runtime.gcBgMarkStartWorkers in goroutine 1
        C:/Program Files (x86)/Go/src/runtime/mgc.go:1217 +0x23

goroutine 45 [GC worker (idle)]:
runtime.gopark(0x1143ba0, 0xa4981f8, 0x1a, 0x14, 0x0)
        C:/Program Files (x86)/Go/src/runtime/proc.go:398 +0xfd fp=0xa68ff94 sp=0xa68ff80 pc=0xcc083d
runtime.gcBgMarkWorker()
        C:/Program Files (x86)/Go/src/runtime/mgc.go:1293 +0xdc fp=0xa68fff0 sp=0xa68ff94 pc=0xc9e50c
runtime.goexit()
        C:/Program Files (x86)/Go/src/runtime/asm_386.s:1363 +0x1 fp=0xa68fff4 sp=0xa68fff0 pc=0xcef771
created by runtime.gcBgMarkStartWorkers in goroutine 1
        C:/Program Files (x86)/Go/src/runtime/mgc.go:1217 +0x23

goroutine 4652 [select]:
runtime.gopark(0x1143d2c, 0x0, 0x9, 0x18, 0x1)
        C:/Program Files (x86)/Go/src/runtime/proc.go:398 +0xfd fp=0x11311ec8 sp=0x11311eb4 pc=0xcc083d
runtime.selectgo(0x11311fd0, 0x11311fc8, 0x0, 0x0, 0x2, 0x1)
        C:/Program Files (x86)/Go/src/runtime/select.go:327 +0xac6 fp=0x11311fa8 sp=0x11311ec8 pc=0xcd1736
github.com/cheggaaa/pb/v3.(*ProgressBar).writer(0xd1be640, 0xd1e8180)
        C:/Users/Jason/go/pkg/mod/github.com/cheggaaa/pb/v3@v3.1.2/pb.go:184 +0x93 fp=0x11311fe4 sp=0x11311fa8 pc=0xfe1173
github.com/cheggaaa/pb/v3.(*ProgressBar).Start.func2()
        C:/Users/Jason/go/pkg/mod/github.com/cheggaaa/pb/v3@v3.1.2/pb.go:178 +0x2c fp=0x11311ff0 sp=0x11311fe4 pc=0xfe107c
runtime.goexit()
        C:/Program Files (x86)/Go/src/runtime/asm_386.s:1363 +0x1 fp=0x11311ff4 sp=0x11311ff0 pc=0xcef771
created by github.com/cheggaaa/pb/v3.(*ProgressBar).Start in goroutine 1
        C:/Users/Jason/go/pkg/mod/github.com/cheggaaa/pb/v3@v3.1.2/pb.go:178 +0x24d
```

If you could let me know what's up or if I can fix this on my side that would be great! and if it's a bug on your guy's side then I wish you all the best in solving it (if it needs solving).
Thanks guys! <3

**Comment by leotaku** [comment]
Hi, thanks for reporting your issue and your nice comments!

The library I have created for generating MOBI/AZW3 books unfortunately requires quite a bit of memory to run, especially if lots of large (image) files are involved. I've documented this issue at leotaku/mobi#4, but unfortunately it has proven harder to fix than I initially expected.

As a temporary fix, I would recommend that you check if your output folder contains a file named `0008.azw3`. If so, delete it, as it is almost certainly corrupted because of the crash. Then, rerun the same command you used to download the manga. Volumes that you have already downloaded will be skipped and with a bit of luck, you should have enough RAM for the command to finish successfully. If not, maybe try freeing up some of your RAM by closing other applications. If none of these suggestions help fix your problem, please report back and I will try to assist you further.

**Comment by jason-anca** [comment]
Hey leotaku!
I appreciate the swift reply and your willingness to help out!
I only got around to testing your solution a few mins ago. I deleted volume 8 `0008.azw3` as you said and attempted to run the command again. It crashes yet again providing a similar output to what I showed previously.
I tried running the command a second time and it had skipped volume 8 again even though the output folder didn't have a `0008.azw3 inside.
Now I'm not running many programs at all and even so I do have 32GB of RAM on this machine and the running command while running only takes up about 1.5GB.

**Comment by leotaku** [comment]
Hmmm, tried to reproduce this error on a Windows 10 VM under various conditions, but I've not been able to do so. Are you currently using the prebuilt version of kojirou available on the release page? If not, could you please try that instead of building kojirou yourself and see if the error persists?
